PRODUCT_COPY_FILES += \
	vendor/motorola/ali/proprietary/lib/libdmengine.so:system/lib/libdmengine.so \
	vendor/motorola/ali/proprietary/lib/libdmengine.so:system/priv-app/DMService/lib/arm/libdmengine.so \
	vendor/motorola/ali/proprietary/lib/libdmjavaplugin.so:system/lib/libdmjavaplugin.so \
	vendor/motorola/ali/proprietary/lib/libdmjavaplugin.so:system/priv-app/DMSservice/lib/arm/libdmjavaplugin.so \
	vendor/motorola/ali/proprietary/lib/libimscamera_jni.so:system/lib/libimscamera_jni.so \
	vendor/motorola/ali/proprietary/lib/lib-imscamera.so:system/lib/lib-imscamera.so \
	vendor/motorola/ali/proprietary/lib/libimsmedia_jni.so:system/lib/libimsmedia_jni.so \
	vendor/motorola/ali/proprietary/lib/lib-imsvideocodec.so:system/lib/lib-imsvideocodec.so \
	vendor/motorola/ali/proprietary/lib/lib-imsvtextutils.so:system/lib/lib-imsvtextutils.so \
	vendor/motorola/ali/proprietary/lib/lib-imsvt.so:system/lib/lib-imsvt.so \
	vendor/motorola/ali/proprietary/lib/lib-imsvtutils.so:system/lib/lib-imsvtutils.so \
	vendor/motorola/ali/proprietary/lib/libqti-perfd-client_system.so:system/lib/libqti-perfd-client_system.so \
	vendor/motorola/ali/proprietary/lib/libqti_performance.so:system/lib/libqti_performance.so \
	vendor/motorola/ali/proprietary/lib/libqti-perfd-client_system.so:system/lib/libqti-perfd-client_system.so \
	vendor/motorola/ali/proprietary/lib/libdiag_system.so:system/lib/libdiag_system.so \
	vendor/motorola/ali/proprietary/lib/vendor.qti.hardware.perf@1.0.so:system/lib/vendor.qti.hardware.perf@1.0.so \
	vendor/motorola/ali/proprietary/lib/vendor.qti.imsrtpservice@1.0.so:system/lib/vendor.qti.imsrtpservice@1.0.so \
	vendor/motorola/ali/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
	vendor/motorola/ali/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
	vendor/motorola/ali/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar \
	vendor/motorola/ali/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
	vendor/motorola/ali/proprietary/framework/com.quicinc.cne.api-V1.0-java.jar:system/framework/com.quicinc.cne.api-V1.0-java.jar \
	vendor/motorola/ali/proprietary/framework/com.quicinc.cne.api-V1.1-java.jar:system/framework/com.quicinc.cne.api-V1.1-java.jar \
	vendor/motorola/ali/proprietary/framework/com.quicinc.cne.constants-V1.0-java.jar:system/framework/com.quicinc.cne.constants-V1.0-java.jar \
	vendor/motorola/ali/proprietary/framework/com.quicinc.cne.constants-V2.0-java.jar:system/framework/com.quicinc.cne.constants-V2.0-java.jar \
	vendor/motorola/ali/proprietary/framework/com.quicinc.cne.constants-V2.1-java.jar:system/framework/com.quicinc.cne.constants-V2.1-java.jar \
	vendor/motorola/ali/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
	vendor/motorola/ali/proprietary/framework/com.quicinc.cne.server-V1.0-java.jar:system/framework/com.quicinc.cne.server-V1.0-java.jar \
	vendor/motorola/ali/proprietary/framework/com.quicinc.cne.server-V2.0-java.jar:system/framework/com.quicinc.cne.server-V2.0-java.jar \
	vendor/motorola/ali/proprietary/framework/com.quicinc.cne.server-V2.1-java.jar:system/framework/com.quicinc.cne.server-V2.1-java.jar \
	vendor/motorola/ali/proprietary/framework/com.quicinc.cne.server-V2.2-java.jar:system/framework/com.quicinc.cne.server-V2.2-java.jar \
	vendor/motorola/ali/proprietary/framework/qti-vzw-ims-internal.jar:system/framework/qti-vzw-ims-internal.jar \
	vendor/motorola/ali/proprietary/framework/vendor.qti.data.factory-V1.0-java.jar:system/framework/vendor.qti.data.factory-V1.0-java.jar \
	vendor/motorola/ali/proprietary/framework/vendor.qti.hardware.data.dynamicdds-V1.0-java.jar:system/framework/vendor.qti.hardware.data.dynamicdds-V1.0-java.jar \
	vendor/motorola/ali/proprietary/framework/vendor.qti.hardware.data.latency-V1.0-java.jar:system/framework/vendor.qti.hardware.data.latency-V1.0-java.jar \
	vendor/motorola/ali/proprietary/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar:system/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar \
	vendor/motorola/ali/proprietary/framework/vendor.qti.ims.rcsconfig-V1.0-java.jar:system/framework/vendor.qti.ims.rcsconfig-V1.0-java.jar \
	vendor/motorola/ali/proprietary/framework/vendor.qti.latency-V2.0-java.jar:system/framework/vendor.qti.latency-V2.0-java.jar \
	vendor/motorola/ali/proprietary/etc/perfservice.rc:system/etc/perfservice.rc \
	vendor/motorola/ali/proprietary/etc/thermal-engine.conf:system/etc/thermal-engine.conf \
	vendor/motorola/ali/proprietary/etc/permissions/com.motorola.camera2.xml:system/etc/permissions/com.motorola.camera2.xml \
	vendor/motorola/ali/proprietary/etc/permissions/com.motorola.camera2.denali.xml:system/etc/permissions/com.motorola.camera2.denali.xml \
	vendor/motorola/ali/proprietary/etc/permissions/privapp-permissions-com.motorola.camera2.xml:system/etc/permissions/privapp-permissions-com.motorola.camera2.xml \
	vendor/motorola/ali/proprietary/etc/permissions/com.motorola.moto.xml:system/etc/permissions/com.motorola.moto.xml \
	vendor/motorola/ali/proprietary/etc/permissions/privapp-permissions-com.android.hotwordenrollment.okgoogle.xml:system/etc/permissions/privapp-permissions-com.android.hotwordenrollment.okgoogle.xml \
	vendor/motorola/ali/proprietary/etc/permissions/privapp-permissions-com.android.hotwordenrollment.tgoogle.xml:system/etc/permissions/privapp-permissions-com.android.hotwordenrollment.tgoogle.xml \
	vendor/motorola/ali/proprietary/etc/permissions/privapp-permissions-com.android.hotwordenrollment.xgoogle.xml:system/etc/permissions/privapp-permissions-com.android.hotwordenrollment.xgoogle.xml \
	vendor/motorola/ali/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
	vendor/motorola/ali/proprietary/etc/permissions/privapp-permissions-org.codeaurora.ims.xml:system/etc/permissions/privapp-permissions-org.codeaurora.ims.xml \
	vendor/motorola/ali/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
	vendor/motorola/ali/proprietary/etc/permissions/com.motorola.omadm.service.xml:system/etc/permissions/com.motorola.omadm.service.xml \
	vendor/motorola/ali/proprietary/etc/permissions/privapp-permissions-com.motorola.omadm.service.xml:system/etc/permissions/privapp-permissions-com.motorola.omadm.service.xml \
	vendor/motorola/ali/proprietary/etc/permissions/privapp-permissions-com.motorola.omadm.sprint.xml:system/etc/permissions/privapp-permissions-com.motorola.omadm.sprint.xml \
	vendor/motorola/ali/proprietary/etc/permissions/privapp-permissions-com.motorola.omadm.vzw.xml:system/etc/permissions/privapp-permissions-com.motorola.omadm.vzw.xml \
	vendor/motorola/ali/proprietary/etc/sysconfig/whitelist_com.android.omadm.service.xml:system/etc/permissions/whitelist_com.android.omadm.service.xml \
	vendor/motorola/ali/proprietary/etc/permissions/privapp-permissions-com.android.sdm.plugins.sprintdm.xml:system/etc/permissions/privapp-permissions-com.android.sdm.plugins.sprintdm.xml \
	vendor/motorola/ali/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml

PRODUCT_PACKAGES += \
	CNEService \
	datastatusnotification \
	ims \
	QtiTelephonyService \
	HotwordEnrollmentOKGoogleCS47L35 \
	HotwordEnrollmentTGoogleCS47L35 \
	HotwordEnrollmentXGoogleCS47L35 \
	qcrilmsgtunnel \
	MotCamera2 \
	SprintDM \
	ConnMOStub \
	DCMOStub \
	DMService \
	DiagMon \
	HiddenMenuLight
